### ISSUE TITLE
Consider removing the 'AddEntityFramework*' call

### ISSUE THREAD

**Issue by mheidari988** [stphnwlsh/CleanMinimalApi#22]
**Describe the bug**
There is a warning related to using `AddEntityFrameworkInMemoryDatabase` and `AddDbContext<MovieReviewsDbContext>` at the same time.

Since you're using AddDbContext, this method already adds the necessary EF Core services to the DI container. You might not need to call AddEntityFrameworkInMemoryDatabase explicitly inside `AddInfrastructure()` extension method in the Infrastructure Layer.

This produces a Warning with the below log message:

`
[Warning] [Microsoft.EntityFrameworkCore.Infrastructure] 'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Consider removing the 'AddEntityFramework*' call, as in most cases it's not needed and may cause conflicts with other products and services registered in the same service provider.
`

**To Reproduce**
1. Run the Application.
2. Check Console Logs.

Cheers.

**Comment by stphnwlsh** [comment]
Hey thanks mate!  I'll take a look
